# categorise scales

bias_change <- c( "AAT approach tendency",
                  "ACS (Attention Control Score)",
                  "AST-R: negative",
                  "AST-R: positive",
                  "ASSIQ",
                  "ASI Benign",
                  "ASI Negative",
                  "Attention bias: social threat",
                  "Attention bias: physical sensations",
                  "Attention bias: positive word",
                  "Attention bias to threat index",
                  "Attention bias to threat index",
                  "Approach-Avoidance Task (AAT)",
                  "ASI",
                  "BAT",
                  "Bias for happy faces",
                  "Bias for angry faces",
                  "Change in attentional bias",
                  "Classic Stroop: Cognitive Flexibilty",
                  "Disengagement (Difficulty Shifting Attention)",
                  "Dot probe reaction time (RT) data",
                  "Congruent reaction time",
                  "Incongruent reaction time",
                  "Neutral reaction time",
                  "Threat reaction time",
                  "EATQ-R ( Attention Control subscale)",
                  "Emotional Stroop Task: Attentional Bias for Life Goals",
                  "Emotional Stroop Task: Attention Bias for Social Threat",
                  "Eye-Tracking Task (NIMH-CheFS Faces)",
                  "Eye-Tracking Task (NimStim Faces)",
                  "FOA overall",
                  "FOA: others",
                  "FOA: self",
                  "GASS",
                  "Idiosyncratic word ratings (selection bias)",
                  "Interpretation Bias",
                  "Benign Interpretation",
                  "Negative Interpretation",
                  "Interpretation bias: Sentence Completion Task",
                  "Anxiety related negative responses",
                  "Interpretation bias: Grammar Decision Task",
                  "Interpretation Bias: Benign Endorsement",
                  "Interpretation Bias: Threat Endorsement",
                  "REC-T",
                  "Recognition rating",
                  "Positive interpretations",
                  "Negative interpretations",
                  "Response Latency",
                  "Single Target Implicit Association Test (stIAT)",
                  "Social Interpretation Bias: Threat Endorsement",
                  "Social Interpretation Bias: Benign Endorsement",
                  "SST: Load",
                  "SST: No Load",
                  "Target and foil sentences",
                  "Target",
                  "Target: positive",
                  "Target: Non-negative",
                  "Target: Negative",
                  "Foils",
                  "Foils: Positive",
                  "Foils: Negative",
                  "The Interpretation Questionnaire",
                  "Threat bias measurement",
                  "Vigilance (Threat Detection Speed)",
                  "WASP: Threat endorsement",
                  "WSAP: Benign endorsement",
                  "WSAP: Threat endorsement",
                  "Valenced Contrast Ratings",
                  "Positive interpretation",
                  "Neutral interpretation",
                  "Negative interpretation"
                  )

general_anx <-c("ADIS-IV-C/P",
                "Analogue anxiety scale",
                "BAI",
                "DASS-Anxiety subscale",
                "DASS - stress subscale",
                "GAD-7",
                "HAM-A",
                "PSWQ",
                "SCARED",
                "STAI",
                "STAI-S",
                "STAI-B",
                "STAI-T",
                "TAI",
                "VAS")

# reverse bias for happy faces 

social_anx <- c("ADIS Clinician-rated anxiety",
                "Anticipated anxiety",
                "Predicted Social Performance",
                "ASSIQ",
                "ASSQ",
                "BASA",
                "BFNE-R",
                "BFNES",
                "Brief Fear of Negative Evaluation Scale (BFNE)",
                "BSPS",
                "C-DSM-IV",
                "CSR",
                "CUSADOS",
                "FPES",
                "Fear of Negative Evaluation (FNE)",
                "IPSM",
                "LSAS",
                "LSAS-CA",
                "LSAS-CA-SR",
                "LSAS (fear subscale)",
                "LSAS-SR",
                "Mini-SPIN",
                "Mini-SPIN-R",
                "MASC",
                "PRCS",
                "RCADS – Social Phobia Subscale",
                "RSES",
                "SAD-D",
                "SADS",
                "SAR-8 (Social Anxiety Symptoms)",
                "SAS-A",
                "SASCI",
                "SASC-R",
                "SAQ-A30",
                "SCARED Social Anxiety Subscale",
                "SCAS",
                "SCAS-c",
                "SCAS SP Child",
                "SIAS",
                "BSIQ",
                "S-SIAS",
                "SIPS",
                "SIT-Social Interaction Task",
                "SPAI",
                "Social Phobia and Anxiety Inventory - 18 Item (SPAI-18)",
                "Social Phobia and Anxiety Inventory - 23 Items (SPAI-23)",
                "Social Phobia and Anxiety Inventory - 26 items (SPAI-26)",
                "Social Phobia and Anxiety Inventory - 45 Items (SPAI-45)",
                "SPAI - social phobia subscale",
                "SPAI-C",
                "SPAI-C 11 item",
                "SPAI-C 26 item",
                "SPAI-C Brief / SPAI -B",
                "SPAI-C",
                "SCID-IV",
                "SCID-IV",
                "SPI",
                "SPIN",
                "SPIN-R",
                "SPS",
                "SPS-6",
                "SPSQ",
                "Subjective anxiety VAS",
                "ASIQ",
                "SPDQ",
                "Rating Form (RF)",
                "Skin conductance amplitudes",
                "Behavioural speech task latency",
                "Behavioural speech task duration",
                "Behavioural interaction task latency",
                "Behavioural interaction task duration",
                "Interaction Anxiety Scale",
                "Heart Rate",
                "Subjective Units of Discomfort Scale (SUDS)",
                "Skin conductance level (Micro Siemens)"
                )

dep <- c( "Analogue mood scale",
          "BDI",
          "BDI-II",
          "BDI-13",
          "CDI",
          "CDRS-R",
          "CES-D",
          "CESD-14",
          "DASS-D",
          "DASS-21",
          "DASS-42",
          "HAM-D",
          "HRSD",
          "IDS",
          "QIDS",
          "IDS-IVR-30",
          "IDS-C-30",
          "MADRS",
          "MAS",
          "MASQ: Anhedonic Depression",
          "PHQ-9",
          "RCADS-MDD",
          "VAMS",
          "Zung Self-Rating Depression Scale (SDS)",
          "PANAS-positive",
          "Dysfunctional Attitudes Scale",
          "Automatic thoughts questionnaire",
          "PTQ",
          "PA",
          "PANAS-negative")

# PANAS-positive/ PTQ / PA needs to be reversed

qol <- c( "CGI-I",
          "CGIS",
          "CGI-C",
          "Change in diagnostic status",
          "GAF",
          "SDS",
          "SF-36",
          "SFQ",
          "Q-LES-Q",
          "QLES-Q General Activities",
          "Q-LES-Q-SF",
          "QOLI",
          "WHOQOL-BREF",
          "WSAS",
          "Brunnsviken Brief Quality of Life Inventory (BBQ)",
          "SCSR",
          "Interpersonal Outcomes: Social Approach",
          "Interpersonal Outcomes: Relationship Satisfaction",
          "BSI")

# SCSR, RSES reverse